<?php
/**
 * รายชื่อ 77 จังหวัดไทย (เรียงตามตัวอักษรไทย)
 */
return [
    ['id' => 'กรุงเทพมหานคร', 'name_th' => 'กรุงเทพมหานคร', 'name_en' => 'Bangkok'],
    ['id' => 'กระบี่', 'name_th' => 'กระบี่', 'name_en' => 'Krabi'],
    ['id' => 'กาญจนบุรี', 'name_th' => 'กาญจนบุรี', 'name_en' => 'Kanchanaburi'],
    ['id' => 'กาฬสินธุ์', 'name_th' => 'กาฬสินธุ์', 'name_en' => 'Kalasin'],
    ['id' => 'กำแพงเพชร', 'name_th' => 'กำแพงเพชร', 'name_en' => 'Kamphaeng Phet'],
    ['id' => 'ขอนแก่น', 'name_th' => 'ขอนแก่น', 'name_en' => 'Khon Kaen'],
    ['id' => 'จันทบุรี', 'name_th' => 'จันทบุรี', 'name_en' => 'Chanthaburi'],
    ['id' => 'ฉะเชิงเทรา', 'name_th' => 'ฉะเชิงเทรา', 'name_en' => 'Chachoengsao'],
    ['id' => 'ชลบุรี', 'name_th' => 'ชลบุรี', 'name_en' => 'Chon Buri'],
    ['id' => 'ชัยนาท', 'name_th' => 'ชัยนาท', 'name_en' => 'Chai Nat'],
    ['id' => 'ชัยภูมิ', 'name_th' => 'ชัยภูมิ', 'name_en' => 'Chaiyaphum'],
    ['id' => 'ชุมพร', 'name_th' => 'ชุมพร', 'name_en' => 'Chumphon'],
    ['id' => 'เชียงราย', 'name_th' => 'เชียงราย', 'name_en' => 'Chiang Rai'],
    ['id' => 'เชียงใหม่', 'name_th' => 'เชียงใหม่', 'name_en' => 'Chiang Mai'],
    ['id' => 'ตรัง', 'name_th' => 'ตรัง', 'name_en' => 'Trang'],
    ['id' => 'ตราด', 'name_th' => 'ตราด', 'name_en' => 'Trat'],
    ['id' => 'ตาก', 'name_th' => 'ตาก', 'name_en' => 'Tak'],
    ['id' => 'นครนายก', 'name_th' => 'นครนายก', 'name_en' => 'Nakhon Nayok'],
    ['id' => 'นครปฐม', 'name_th' => 'นครปฐม', 'name_en' => 'Nakhon Pathom'],
    ['id' => 'นครพนม', 'name_th' => 'นครพนม', 'name_en' => 'Nakhon Phanom'],
    ['id' => 'นครราชสีมา', 'name_th' => 'นครราชสีมา', 'name_en' => 'Nakhon Ratchasima'],
    ['id' => 'นครศรีธรรมราช', 'name_th' => 'นครศรีธรรมราช', 'name_en' => 'Nakhon Si Thammarat'],
    ['id' => 'นครสวรรค์', 'name_th' => 'นครสวรรค์', 'name_en' => 'Nakhon Sawan'],
    ['id' => 'นนทบุรี', 'name_th' => 'นนทบุรี', 'name_en' => 'Nonthaburi'],
    ['id' => 'นราธิวาส', 'name_th' => 'นราธิวาส', 'name_en' => 'Narathiwat'],
    ['id' => 'น่าน', 'name_th' => 'น่าน', 'name_en' => 'Nan'],
    ['id' => 'บึงกาฬ', 'name_th' => 'บึงกาฬ', 'name_en' => 'Bueng Kan'],
    ['id' => 'บุรีรัมย์', 'name_th' => 'บุรีรัมย์', 'name_en' => 'Buri Ram'],
    ['id' => 'ปทุมธานี', 'name_th' => 'ปทุมธานี', 'name_en' => 'Pathum Thani'],
    ['id' => 'ประจวบคีรีขันธ์', 'name_th' => 'ประจวบคีรีขันธ์', 'name_en' => 'Prachuap Khiri Khan'],
    ['id' => 'ปราจีนบุรี', 'name_th' => 'ปราจีนบุรี', 'name_en' => 'Prachin Buri'],
    ['id' => 'ปัตตานี', 'name_th' => 'ปัตตานี', 'name_en' => 'Pattani'],
    ['id' => 'พระนครศรีอยุธยา', 'name_th' => 'พระนครศรีอยุธยา', 'name_en' => 'Phra Nakhon Si Ayutthaya'],
    ['id' => 'พะเยา', 'name_th' => 'พะเยา', 'name_en' => 'Phayao'],
    ['id' => 'พังงา', 'name_th' => 'พังงา', 'name_en' => 'Phang Nga'],
    ['id' => 'พัทลุง', 'name_th' => 'พัทลุง', 'name_en' => 'Phatthalung'],
    ['id' => 'พิจิตร', 'name_th' => 'พิจิตร', 'name_en' => 'Phichit'],
    ['id' => 'พิษณุโลก', 'name_th' => 'พิษณุโลก', 'name_en' => 'Phitsanulok'],
    ['id' => 'เพชรบุรี', 'name_th' => 'เพชรบุรี', 'name_en' => 'Phetchaburi'],
    ['id' => 'เพชรบูรณ์', 'name_th' => 'เพชรบูรณ์', 'name_en' => 'Phetchabun'],
    ['id' => 'แพร่', 'name_th' => 'แพร่', 'name_en' => 'Phrae'],
    ['id' => 'ภูเก็ต', 'name_th' => 'ภูเก็ต', 'name_en' => 'Phuket'],
    ['id' => 'มหาสารคาม', 'name_th' => 'มหาสารคาม', 'name_en' => 'Maha Sarakham'],
    ['id' => 'มุกดาหาร', 'name_th' => 'มุกดาหาร', 'name_en' => 'Mukdahan'],
    ['id' => 'แม่ฮ่องสอน', 'name_th' => 'แม่ฮ่องสอน', 'name_en' => 'Mae Hong Son'],
    ['id' => 'ยโสธร', 'name_th' => 'ยโสธร', 'name_en' => 'Yasothon'],
    ['id' => 'ยะลา', 'name_th' => 'ยะลา', 'name_en' => 'Yala'],
    ['id' => 'ร้อยเอ็ด', 'name_th' => 'ร้อยเอ็ด', 'name_en' => 'Roi Et'],
    ['id' => 'ระนอง', 'name_th' => 'ระนอง', 'name_en' => 'Ranong'],
    ['id' => 'ระยอง', 'name_th' => 'ระยอง', 'name_en' => 'Rayong'],
    ['id' => 'ราชบุรี', 'name_th' => 'ราชบุรี', 'name_en' => 'Ratchaburi'],
    ['id' => 'ลพบุรี', 'name_th' => 'ลพบุรี', 'name_en' => 'Lop Buri'],
    ['id' => 'ลำปาง', 'name_th' => 'ลำปาง', 'name_en' => 'Lampang'],
    ['id' => 'ลำพูน', 'name_th' => 'ลำพูน', 'name_en' => 'Lamphun'],
    ['id' => 'เลย', 'name_th' => 'เลย', 'name_en' => 'Loei'],
    ['id' => 'ศรีสะเกษ', 'name_th' => 'ศรีสะเกษ', 'name_en' => 'Si Sa Ket'],
    ['id' => 'สกลนคร', 'name_th' => 'สกลนคร', 'name_en' => 'Sakon Nakhon'],
    ['id' => 'สงขลา', 'name_th' => 'สงขลา', 'name_en' => 'Songkhla'],
    ['id' => 'สตูล', 'name_th' => 'สตูล', 'name_en' => 'Satun'],
    ['id' => 'สมุทรปราการ', 'name_th' => 'สมุทรปราการ', 'name_en' => 'Samut Prakan'],
    ['id' => 'สมุทรสงคราม', 'name_th' => 'สมุทรสงคราม', 'name_en' => 'Samut Songkhram'],
    ['id' => 'สมุทรสาคร', 'name_th' => 'สมุทรสาคร', 'name_en' => 'Samut Sakhon'],
    ['id' => 'สระแก้ว', 'name_th' => 'สระแก้ว', 'name_en' => 'Sa Kaeo'],
    ['id' => 'สระบุรี', 'name_th' => 'สระบุรี', 'name_en' => 'Saraburi'],
    ['id' => 'สิงห์บุรี', 'name_th' => 'สิงห์บุรี', 'name_en' => 'Sing Buri'],
    ['id' => 'สุโขทัย', 'name_th' => 'สุโขทัย', 'name_en' => 'Sukhothai'],
    ['id' => 'สุพรรณบุรี', 'name_th' => 'สุพรรณบุรี', 'name_en' => 'Suphan Buri'],
    ['id' => 'สุราษฎร์ธานี', 'name_th' => 'สุราษฎร์ธานี', 'name_en' => 'Surat Thani'],
    ['id' => 'สุรินทร์', 'name_th' => 'สุรินทร์', 'name_en' => 'Surin'],
    ['id' => 'หนองคาย', 'name_th' => 'หนองคาย', 'name_en' => 'Nong Khai'],
    ['id' => 'หนองบัวลำภู', 'name_th' => 'หนองบัวลำภู', 'name_en' => 'Nong Bua Lam Phu'],
    ['id' => 'อ่างทอง', 'name_th' => 'อ่างทอง', 'name_en' => 'Ang Thong'],
    ['id' => 'อำนาจเจริญ', 'name_th' => 'อำนาจเจริญ', 'name_en' => 'Amnat Charoen'],
    ['id' => 'อุดรธานี', 'name_th' => 'อุดรธานี', 'name_en' => 'Udon Thani'],
    ['id' => 'อุตรดิตถ์', 'name_th' => 'อุตรดิตถ์', 'name_en' => 'Uttaradit'],
    ['id' => 'อุทัยธานี', 'name_th' => 'อุทัยธานี', 'name_en' => 'Uthai Thani'],
    ['id' => 'อุบลราชธานี', 'name_th' => 'อุบลราชธานี', 'name_en' => 'Ubon Ratchathani'],
];
